### ISSUE TITLE
Signature: Adding .jpg or .png image crashes PDF4QT

### ISSUE THREAD

**Issue by cweiske** [JakubMelka/PDF4QT#179]
I am trying to add a .png signature image, but PDF4QT crashes. Adding bitmaps should work since #27.

Steps to reproduce (just as in https://github.com/JakubMelka/PDF4QT/issues/26#issuecomment-1738815918):

1. Enable signature plugin in options and restart PDF4QT editor
2. Open PDF
3. Activate signature creator
4. Click "Create SVG image"
5. In "File Open" dialog, switch type to jpg or png
6. Select jpg/png file
7. PDF4QT crashes

This happens on Debian unstable, PDF4QT AppImage from https://github.com/JakubMelka/PDF4QT/actions/runs/8883454760 (commit 
c9b262f)

**Comment by JakubMelka** [comment]
Hello @cweiske, I have released AppImage version 1.4.0.0. Could you please try this version?

**Comment by cweiske** [comment]
I will when I get back from vacation.

**Comment by cweiske** [comment]
With 1.4.0, the crash does not happen when selecting the image file in the file picker anymore - but when placing the image in the PDF.

Steps to reproduce crash:

1. Enable signature plugin in options and restart PDF4QT editor
2. Open PDF
3. Activate signature creator
4. Click "Create SVG image"
5. In "File Open" dialog, switch type to jpg or png
6. Select jpg/png file (closes file chooser)
7. Move mouse to see image start point selector
8. Click on PDF to begin placing the image
9. PDF4QT crashes

**Comment by tompro** [comment]
Same issue with PNG files (app crash). When using SVG the image can be placed and looks good but vanishes when document is saved and then reopend.

**Comment by JakubMelka** [comment]
Hello @cweiske, @tompro, could you please try the newest "flatpak" version? I think it should be solved.

**Comment by cweiske** [comment]
I'm not sure how to download that flatpak version. Also, did you stop providing the appimage?

- In [Github Actions](https://github.com/JakubMelka/PDF4QT/actions), I see the 
"Issue #229: Can't add picture to PDF" build from 4 days ago which has a deb file for ubuntu, but I'm on debian and it doesn't work since I have qt 6.7 and the deb needs 6.8.
- The "Linux_flatpak" tasks on github actions all failed
- https://flathub.org/apps/io.github.JakubMelka.Pdf4qt shows version 1.4.0, "6 months ago
(Built 19 days ago)" which does not seem right.

**Comment by JakubMelka** [comment]
@cweiske, please try https://github.com/JakubMelka/PDF4QT/actions/runs/12526162017

**Comment by cweiske** [comment]
Adding a .png or .jpg image does not crash PDF4QT anymore!
Unfortunately, when saving the pdf, the added images get lost. When opening the saved file with PDF4QT or a different PDF viewer, the images is gone.

**Comment by JakubMelka** [comment]
@cweiske did you click button to confirm changes, before you saved the document?

**Comment by cweiske** [comment]
No, I didn't know there is a button. When saving + closing the PDF file, PDF4QT did not ask for confirmation.

Even now that I know that there should be a button - I cannot find it. Attached is a screenshot:
![2025-01-02 pdf4qt signature](https://github.com/user-attachments/assets/d3f9a7ec-25e0-4b5b-972b-d29c30273750)

Here I again have the problem that I can't maximize the window because it is higher than my full HD screen - similar to #180, but only when the signature sidebar is open (I guess the signature toolbox content is not scrollable).

When manually moving the window higher, I still do not see any button that looks like a confirmation button:
![2025-01-02 sigtestRL pdf- - PDF4QT Editor_002](https://github.com/user-attachments/assets/2980d101-1883-4610-8e21-b77aac1477be)

**Comment by JakubMelka** [comment]
@cweiske, you are running the signature editor plugin. Please start the regular editor plugin (in the options menu, you should enable it - now it looks it is disabled).

**Comment by cweiske** [comment]
I don't understand why there is a signature creator button to add signature images, which does not work.
I don't understand why I have to enable an editor plugin when I'm already in the PDF editor.

I did enable the editor plugin, added a .jpg image, got asked if the changes should be written, and I confirmed. Then the application crashed:
```
(gdb) terminate called after throwing an instance of 'pdf::PDFException'
  what():  std::exception
bt
No stack.
(gdb) bt full
No stack.
```

(Another problem is that the image file open dialog does not offer a "all supported image types" filter, and I manually have to choose the file type before selecting a file.)

**Comment by JakubMelka** [comment]
@cweiske, could you please send me a file, where the crash occured?

**Comment by cweiske** [comment]
PDF file: https://regionalbusleipzig.de/media/pages/tickets/schueler-azubis/7f405ccd76-1712565425/formular_bestellung_bildungsticket_rl.pdf

Steps to reproduce:

1. Download and unzip appimage from https://github.com/JakubMelka/PDF4QT/actions/runs/13376152104
2. Start appimage
3. Click "Editor"
4. Open `formular_bestellung_bildungsticket_rl.pdf`
5. Tools > Options > Plugins: Enable "Editor"
6. Tools > Editor > Edit page content: Opens sidebar on the left
7. Click "Create SVG image" button in the toolbox.
8. In the file open dialog, change the filter to "jpeg image (*.jpg)"
9. PDF view shows large crosshair, click to set start point
10. Move mouse and click to set end point of image. Image appears.
11. Tools > Editor > Edit page content.
12. Confirmation dialog: "The changes to the page content will be written to the document. Do you want to continue?" -> Click "yes"
13. Crash

**Comment by cweiske** [comment]
The error still happens with 1.5.0.0.

With the first try, it seemed to work (no crash) - but all the text was removed from the page I added the image to. Then I added a second image, and it crashed again.

Then I downloaded the pdf file again, added the image and it crashed immediately.

Terminal output:
> terminate called after throwing an instance of 'pdf::PDFException'
> what():  std::exception

gdb backtrace:
```
[Thread 0x7fffd6c006c0 (LWP 13623) exited]
terminate called after throwing an instance of 'pdf::PDFException'
  what():  std::exception

Thread 1 "Pdf4QtEditor" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: Datei oder Verzeichnis nicht gefunden
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff469e9ff in __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:89
#2  0x00007ffff4649cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff46324ac in __GI_abort () at ./stdlib/abort.c:73
#4  0x00007ffff48a1a3d in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff48b344a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff48a15e9 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff48b36c8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6aed563 in pdf::PDFFont::createFont(pdf::PDFObject const&, QByteArray, pdf::PDFDocument const*) [clone .cold] ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
#9  0x00007ffff6e23d15 in pdf::PDFPageContentEditorContentStreamBuilder::selectFont(QByteArray const&) () from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
#10 0x00007ffff6e25e6c in pdf::PDFPageContentEditorContentStreamBuilder::writeTextCommand(QTextStream&, QXmlStreamReader const&) ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
#11 0x00007ffff6e2651e in pdf::PDFPageContentEditorContentStreamBuilder::writeText(QTextStream&, QString const&) () from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
#12 0x00007ffff6e27fca in pdf::PDFPageContentEditorContentStreamBuilder::writeEditedElement(pdf::PDFEditedPageContentElement const*) ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
#13 0x00007fffefeecd07 in pdfplugin::EditorPlugin::updatePageContent(long, std::vector<pdf::PDFPageContentElement const*, std::allocator<pdf::PDFPageContentElement const*> > const&, pdf::PDFDocumentBuilder*) () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
#14 0x00007fffefeee967 in pdfplugin::EditorPlugin::save() () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
#15 0x00007fffefef1ee0 in pdfplugin::EditorPlugin::onSetActive(bool) () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
```

full backtrace:
```
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {1}}
        ret = <optimized out>
#1  0x00007ffff469e9ff in __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:89
No locals.
#2  0x00007ffff4649cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff46324ac in __GI_abort () at ./stdlib/abort.c:73
        act = {__sigaction_handler = {sa_handler = 0x7ffff47effd0 <_IO_file_jumps>, sa_sigaction = 0x7ffff47effd0 <_IO_file_jumps>}, sa_mask = {__val = {140737295361379, 1, 
              140737293924562, 1, 10, 140737288406272, 140737488334976, 140737488334608, 140737293928185, 140737295361248, 140737293929523, 140737295361248, 10, 140737288406272, 
              140737293913242, 140737297277104}}, sa_flags = -192207532, sa_restorer = 0x7ffff49c60b0}
#4  0x00007ffff48a1a3d in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff48b344a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff48a15e9 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007ffff48b36c8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x00007ffff6aed563 in pdf::PDFFont::createFont(pdf::PDFObject const&, QByteArray, pdf::PDFDocument const*) [clone .cold] ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
No symbol table info available.
#9  0x00007ffff6e23d15 in pdf::PDFPageContentEditorContentStreamBuilder::selectFont(QByteArray const&) () from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
No symbol table info available.
#10 0x00007ffff6e25e6c in pdf::PDFPageContentEditorContentStreamBuilder::writeTextCommand(QTextStream&, QXmlStreamReader const&) ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
No symbol table info available.
#11 0x00007ffff6e2651e in pdf::PDFPageContentEditorContentStreamBuilder::writeText(QTextStream&, QString const&) () from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
No symbol table info available.
#12 0x00007ffff6e27fca in pdf::PDFPageContentEditorContentStreamBuilder::writeEditedElement(pdf::PDFEditedPageContentElement const*) ()
   from /tmp/.mount_PDF4QTmaFXkw/usr/bin/../lib/libPdf4QtLibCore.so.1.5.0.0
No symbol table info available.
#13 0x00007fffefeecd07 in pdfplugin::EditorPlugin::updatePageContent(long, std::vector<pdf::PDFPageContentElement const*, std::allocator<pdf::PDFPageContentElement const*> > const&, pdf::PDFDocumentBuilder*) () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
No symbol table info available.
#14 0x00007fffefeee967 in pdfplugin::EditorPlugin::save() () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
No symbol table info available.
#15 0x00007fffefef1ee0 in pdfplugin::EditorPlugin::onSetActive(bool) () from /tmp/.mount_PDF4QTmaFXkw/usr/lib/pdf4qt/libEditorPlugin.so.1.5.0.0
No symbol table info available.
```

**Comment by cweiske** [comment]
The build failed: https://github.com/JakubMelka/PDF4QT/actions/runs/18618476738/job/53086360647
